name: peerdart
version: 0.5.4
homepage: https://github.com/MuhammedKpln/peerdart
description: Simple peer-to-peer with WebRTC for Dart. PeerJS port for Flutter.
repository: https://github.com/MuhammedKpln/peerdart
environment: 
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=1.22.0'
dependencies: 
  http: ^1.1.0
  uuid: ^3.0.6
  flutter_webrtc:
    git:
      url: https://github.com/flutter-webrtc/flutter-webrtc.git
      ref: duan/downgrade-to-flutter-3.24.5
  web_socket_channel: ^2.4.0
  events_emitter: ^0.5.2
dev_dependencies: 
  lints: ^2.0.0
  flutter_test: 
    sdk: flutter
